# 定义网站的名称，会显示在页面标题、导航栏等位置
site_name: KlipperScreen
# 定义网站的官方访问地址（URL），用于生成站点地图、链接跳转等
site_url: https://klipperscreen.readthedocs.io
# 定义网站的描述信息，会用于 SEO（搜索引擎优化）、页面 meta 标签等
site_description: >-
  KlipperScreen documentation.

# 定义代码仓库的展示名称（会显示在文档页面的仓库链接处）
repo_name: KlipperScreen/KlipperScreen/
# 定义代码仓库的实际访问地址，文档页面会生成指向该地址的跳转链接
repo_url: https://github.com/gushuangquan18/HuaFu-KlipperScreen.git
nav:
    - Home: index.md
    - FAQ: FAQ.md
    - Setup:
      - Hardware: Hardware.md
      - Hardware specific:
        - GPIO 3.5": Hardware/GPIO_35.md
        - HDMI: Hardware/HDMI.md
      - Installation.md
      - Updating.md
      - Configuration.md
      - Quicktips.md
      - Macros: macros.md
      - Thumbnails.md
      - Remote screens:
        - VNC.md
        - Xserver-XSDL (Android): Android.md
        - Multi_instance.md
    - Troubleshooting:
      - First Steps/Log: Troubleshooting.md
      - Network: Troubleshooting/Network.md
      - Physical install: Troubleshooting/Physical_Install.md
      - Wrong Framebuffer: Troubleshooting/Framebuffer.md
      - Framebuffer ID: Troubleshooting/Framebuffer_id.md
      - Screen Rotation: Troubleshooting/Rotation.md
      - Touch: Troubleshooting/Touch_issues.md
      - Virtual Console Error: Troubleshooting/VC_ERROR.md
      - FBturbo: Troubleshooting/FBturbo.md
      - Last resort: Troubleshooting/Last_resort.md
    - Screenshots: Panels.md
    - Panels:
      - Bed Level/Screws: Panels/Screws.md
      - Job_status/Printing: Panels/Job_status.md
      - Temperature: Panels/Temperature.md
      - Z Calibrate: Panels/Zcalibrate.md
    - Theming.md
    - Translations.md
    - Changelog: changelog.md
    - Breaking Changes: breaking.md
    - Developers.md
    - Contact.md
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: deep purple

plugins:
    - search

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/KlipperScreen/KlipperScreen/
      - icon: fontawesome/brands/discord
        link: https://discord.klipper3d.org/
      - icon: fontawesome/brands/python

extra_css:
      - stylesheets/extra.css
