[menu bed_mesh_calibration]
name:  {{ gettext('bed_mesh_calibration') }}
type: Grid

[menu bed_mesh_calibration head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 560
v_height: 100
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu bed_mesh_calibration head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
icon: back
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 90
v_button_height: 80
width: 50
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 50
v_height: 50
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu bed_mesh_calibration head_grid calibration_label]
name:  {{ gettext('Calibration Label') }}
type: Label
value:  {{ gettext('Bed Mesh Auto Calibration') }}
column: 1
row: 0
columnspan: 1
rowspan: 1
v_column: 1
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu bed_mesh_calibration bed_mesh_calibration_body_grid]
name:  {{ gettext('Bed Mesh Calibration Body grid') }}
type: Grid
width: 940
height: 500
column: 0
row: 1
columnspan: 4
rowspan: 5
v_width: 570
v_height: 820
v_column: 0
v_row: 1
v_columnspan: 2
v_rowspan: 5

[menu bed_mesh_calibration bed_mesh_calibration_body_grid bed_mesh_calibration_message_grid]
name:  {{ gettext('Bed Mesh Calibration Message Grid') }}
type: Grid
width: 550
height: 500
column: 0
row: 0
columnspan: 3
rowspan: 7
v_width: 570
v_height: 360
v_column: 0
v_row: 0
v_columnspan: 3
v_rowspan: 5

[menu bed_mesh_calibration bed_mesh_calibration_body_grid bed_mesh_calibration_message_grid bed_mesh_calibration_message]
name:  {{ gettext('Bed Mesh Calibration Message') }}
type: TextView
value:  {{ gettext('Bed Mesh Auto Calibration') }}
column: 0
row: 0
columnspan: 1
rowspan: 1
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu bed_mesh_calibration bed_mesh_calibration_body_grid bed_mesh_calibration_image_grid]
name:  {{ gettext('Bed Mesh Calibration Image Grid') }}
type: Grid
column_homogeneous: True
width: 400
height: 420
column: 3
row: 0
columnspan: 2
rowspan: 6
v_width: 570
v_height: 360
v_column: 0
v_row: 5
v_columnspan: 3
v_rowspan: 5

[menu bed_mesh_calibration bed_mesh_calibration_body_grid bed_mesh_calibration_image_grid bed_mesh_calibration_image]
name:  {{ gettext('Bed Mesh Calibration Image') }}
type: Image
src:  {{ gettext('images/sport_calibration.jpg') }}
width: 360
height: 400
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 300
v_height: 275
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu bed_mesh_calibration bed_mesh_calibration_body_grid start_button]
name:  {{ gettext('Start Button') }}
type: Button
value:  {{ gettext('Start') }}
method: bed_mesh_calibration
style: next_level
hexpand: False
vexpand: False
button_width: 400
button_height: 60
v_button_width: 570
v_button_height: 80
column: 3
row: 6
columnspan: 2
rowspan: 1
v_column: 0
v_row: 10
v_columnspan: 1
v_rowspan: 1