[menu calibration]
name:  {{ gettext('calibration') }}
type: Grid

[menu calibration head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu calibration head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu calibration head_grid calibration_label]
name:  {{ gettext('Calibration Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('Calibration') }}

[menu calibration calibration_body_grid]
name:  {{ gettext('Calibration Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu calibration calibration_body_grid bed_mesh_calibration]
name:  {{ gettext('Bed Mesh Calibration') }}
type: Button
panel: bed_mesh_calibration
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 60
button_width: 940

[menu calibration calibration_body_grid bed_mesh_calibration bed_mesh_calibration_grid]
name:  {{ gettext('Bed Mesh Calibration Grid') }}
type: Grid
width: 940
height: 60

[menu calibration calibration_body_grid bed_mesh_calibration bed_mesh_calibration_grid bed_mesh_calibration_label]
name:  {{ gettext('Bed Mesh Calibration Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('Bed Mesh Auto Calibration') }}

[menu calibration calibration_body_grid bed_mesh_calibration bed_mesh_calibration_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu calibration calibration_body_grid bed_mesh_calibration bed_mesh_calibration_grid right_arrow_icon]
name:  {{ gettext('Right Arrow Icon') }}
type: Image
width: 30
height: 40
row: 0
column: 2
rowspan: 1
columnspan: 1
src:  {{ gettext('images/right_arrow.png') }}

[menu calibration calibration_body_grid z_offset_calibration]
name:  {{ gettext('Z Offset Calibration') }}
type: Button
panel: z_offset_calibration
row: 1
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 60
button_width: 940

[menu calibration calibration_body_grid z_offset_calibration z_offset_calibration_grid]
name:  {{ gettext('Z Offset Calibration Grid') }}
type: Grid
width: 940
height: 60

[menu calibration calibration_body_grid z_offset_calibration z_offset_calibration_grid z_offset_calibration_label]
name:  {{ gettext('Z Offset Calibration Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('Z Offset Calibration') }}

[menu calibration calibration_body_grid z_offset_calibration z_offset_calibration_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu calibration calibration_body_grid z_offset_calibration z_offset_calibration_grid right_arrow_icon]
name:  {{ gettext('Right Arrow Icon') }}
type: Image
width: 30
height: 40
row: 0
column: 2
rowspan: 1
columnspan: 1
src:  {{ gettext('images/right_arrow.png') }}