[menu chassis_light]
name:  {{ gettext('chassis_light') }}
type: Grid

[menu chassis_light head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu chassis_light head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu chassis_light head_grid chassis_light_label]
name:  {{ gettext('Chassis Light Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('机箱灯模式') }}

[menu chassis_light chassis_light_body_grid]
name:  {{ gettext('Chassis Light Body Grid') }}
type: Grid
width: 930
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4
row_spacing: 1

[menu chassis_light chassis_light_body_grid chassis_light_message]
name:  {{ gettext('Chassis Light Message') }}
type: Label
row: 0
column: 0
rowspan: 4
columnspan: 1
value:  {{ gettext('手动模式\n打印机仅在AI检测需要灯光时自动开启机箱灯\n节能模式') }}

[menu chassis_light chassis_light_body_grid manual_mode]
name:  {{ gettext('Manual Mode') }}
type: Button
row: 1
column: 1
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 110
button_width: 420
value:  {{ gettext('手动模式') }}
style: speed_control_button

[menu chassis_light chassis_light_body_grid power_saving_mode]
name:  {{ gettext('Power Saving Mode') }}
type: Button
row: 2
column: 1
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 110
button_width: 420
value:  {{ gettext('节能模式') }}
style: speed_control_button