[menu consumables_menu]
name:  {{ gettext('consumables_menu') }}
type: Grid

[menu consumables_menu consumables_control]
name:  {{ gettext('Consumables Control') }}
type: Button
icon: consumables
row: 0
column: 0
rowspan: 1
columnspan: 1
method: show_dialog