[menu consumables_menu]
name:  {{ gettext('consumables_menu') }}
type: Grid

[menu consumables_menu t0_extruder_consumables_control]
name:  {{ gettext('T0 Extruder Consumables Control') }}
type: Button
icon: consumables_left
row: 0
column: 0
rowspan: 1
columnspan: 1
method: consumables_dialog