[menu disk_messages]
name:  {{ gettext('disk_messages') }}
type: Grid

[menu disk_messages head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu disk_messages head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu disk_messages head_grid disk_messages_label]
name:  {{ gettext('Disk Messages Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('USB 存储') }}

[menu disk_messages disk_messages_body_grid]
name:  {{ gettext('Disk Messages Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu disk_messages disk_messages_body_grid disk_messages_memory_grid]
name:  {{ gettext('Disk Messages Memory Grid') }}
type: Grid
width: 900
height: 80
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu disk_messages disk_messages_body_grid disk_messages_memory_grid disk_messages_memory_label]
name:  {{ gettext('Disk Messages Memory Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('存储') }}

[menu disk_messages disk_messages_body_grid disk_messages_memory_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu disk_messages disk_messages_body_grid disk_messages_memory_grid disk_messages_memory_size]
name:  {{ gettext('Disk Messages Memory Size') }}
type: Label
row: 0
column: 3
rowspan: 1
columnspan: 1
value:  {{ gettext('17.7GB/32GB') }}

[menu disk_messages disk_messages_body_grid pop_up_grid]
name:  {{ gettext('Pop Up Grid') }}
type: Grid
width: 900
height: 80
row: 1
column: 0
rowspan: 1
columnspan: 1

[menu disk_messages disk_messages_body_grid pop_up_grid pop_up_label]
name:  {{ gettext('Pop Up Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('弹出') }}

[menu disk_messages disk_messages_body_grid pop_up_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu disk_messages disk_messages_body_grid pop_up_grid settings_right_arrow_icon]
name:  {{ gettext('Settings Right Arrow Icon') }}
type: Image
width: 30
height: 40
row: 0
column: 2
rowspan: 1
columnspan: 1
src:  {{ gettext('images/right_arrow.png') }}

[menu disk_messages disk_messages_body_grid format_disk_grid]
name:  {{ gettext('Format Disk Grid') }}
type: Grid
width: 900
height: 80
row: 2
column: 0
rowspan: 1
columnspan: 1

[menu disk_messages disk_messages_body_grid format_disk_grid format_disk_label]
name:  {{ gettext('Format Disk Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('格式化外部存储') }}

[menu disk_messages disk_messages_body_grid format_disk_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu disk_messages disk_messages_body_grid format_disk_grid settings_right_arrow_icon]
name:  {{ gettext('Settings Right Arrow Icon') }}
type: Image
width: 30
height: 40
row: 0
column: 2
rowspan: 1
columnspan: 1
src:  {{ gettext('images/right_arrow.png') }}