[menu firmware_information]
name:  {{ gettext('firmware_information') }}
type: Grid

[menu firmware_information head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu firmware_information head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu firmware_information head_grid firmware_information_label]
name:  {{ gettext('Firmware Information Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('固件') }}

[menu firmware_information head_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 2
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu firmware_information head_grid next_level]
name:  {{ gettext('Next Level') }}
type: Button
panel: matching_consumables
row: 0
column: 4
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 15
button_width: 150
value:  {{ gettext('更新') }}
style: next_level

[menu firmware_information firmware_information_body_grid]
name:  {{ gettext('Firmware Information Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu firmware_information firmware_information_body_grid printer_firmware_information_grid]
name:  {{ gettext('Printer Firmware Information Grid') }}
type: Grid
width: 900
height: 80
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu firmware_information firmware_information_body_grid printer_firmware_information_grid printer_firmware_information_label]
name:  {{ gettext('Printer Firmware Information Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('HUAFU Test1') }}

[menu firmware_information firmware_information_body_grid printer_firmware_information_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu firmware_information firmware_information_body_grid printer_firmware_information_grid printer_firmware_information_version]
name:  {{ gettext('Printer Firmware Information Version') }}
type: Label
row: 0
column: 3
rowspan: 1
columnspan: 1
value:  {{ gettext('01.02.02.00') }}

[menu firmware_information firmware_information_body_grid pump_firmware_information_grid]
name:  {{ gettext('Pump Firmware Information Grid') }}
type: Grid
width: 900
height: 80
row: 1
column: 0
rowspan: 1
columnspan: 1

[menu firmware_information firmware_information_body_grid pump_firmware_information_grid pump_firmware_information_label]
name:  {{ gettext('Pump Firmware Information Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('气泵') }}

[menu firmware_information firmware_information_body_grid pump_firmware_information_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu firmware_information firmware_information_body_grid pump_firmware_information_grid pump_firmware_information_version]
name:  {{ gettext('Pump Firmware Information Version') }}
type: Label
row: 0
column: 3
rowspan: 1
columnspan: 1
value:  {{ gettext('03.00.21.29') }}

[menu firmware_information firmware_information_body_grid offline_update_firmware_information_grid]
name:  {{ gettext('Offline Update Firmware Information Grid') }}
type: Grid
width: 900
height: 80
row: 2
column: 0
rowspan: 1
columnspan: 1

[menu firmware_information firmware_information_body_grid offline_update_firmware_information_grid offline_update_firmware_information_label]
name:  {{ gettext('Offline Update Firmware Information Label') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('离线升级') }}