[menu home_menu]
name:  {{ gettext('home_menu') }}
type: Grid

[menu home_menu up_grid]
name:  {{ gettext('Up Grid') }}
type: Grid
width: 900
height: 310
row: 0
column: 0
rowspan: 1
columnspan: 1
row_spacing: 15
column_spacing: 10

[menu home_menu up_grid 3d_printer_model]
name:  {{ gettext('3D Printer Model') }}
type: Image
width: 270
height: 270
row: 0
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/3D_printer.png') }}

[menu home_menu up_grid tag]
name:  {{ gettext('Tag') }}
type: Image
width: 6
height: 40
row: 0
column: 1
rowspan: 1
columnspan: 1
src:  {{ gettext('images/tag_blue.png') }}

[menu home_menu up_grid interactive_message]
name:  {{ gettext('Interactive Message') }}
type: Label
row: 0
column: 2
rowspan: 1
columnspan: 1
value:  {{ gettext('Today is another wonderful day!') }}

[menu home_menu down_grid]
name:  {{ gettext('Down Grid') }}
type: Grid
width: 900
height: 210
row: 1
column: 0
rowspan: 1
columnspan: 1

[menu home_menu down_grid print_file_list]
name:  {{ gettext('Print File List') }}
type: Button
panel: print_file_list
row: 0
column: 0
rowspan: 1
columnspan: 1
connect:  {{ gettext('clicked') }}
method: go_to_next_interface

[menu home_menu down_grid print_file_list print_file_list_grid]
name:  {{ gettext('Print File List Grid') }}
type: Grid
width: 400
height: 190
row: 0
column: 0
rowspan: 1
columnspan: 1
column_spacing: 1

[menu home_menu down_grid print_file_list print_file_list_grid modeling_graphics]
name:  {{ gettext('Modeling Graphics') }}
type: Image
width: 150
height: 150
row: 0
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/home_modeling_graphics.png') }}

[menu home_menu down_grid print_file_list print_file_list_grid print_file_label]
name:  {{ gettext('Print File Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('打印文件') }}

[menu home_menu down_grid lower_right_grid]
name:  {{ gettext('Lower_Right_Grid') }}
type: Grid
width: 500
height: 190
row: 0
column: 1
rowspan: 1
columnspan: 1

[menu home_menu down_grid lower_right_grid nozzle_extruder]
name:  {{ gettext('Nozzle Extruder') }}
type: Button
panel: printer_control_menu
row: 0
column: 0
rowspan: 1
columnspan: 1
connect:  {{ gettext('clicked') }}
style: color4

[menu home_menu down_grid lower_right_grid nozzle_extruder nozzle_extruder_grid]
name:  {{ gettext('Nozzle Extruder Grid') }}
type: Grid
width: 100
height: 190
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu home_menu down_grid lower_right_grid nozzle_extruder nozzle_extruder_grid nozzle1_icon]
name:  {{ gettext('Nozzle1 Icon') }}
type: Image
width: 40
height: 40
row: 0
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/nozzle.png') }}

[menu home_menu down_grid lower_right_grid nozzle_extruder nozzle_extruder_grid nozzle1_temperature]
name:  {{ gettext('Nozzle1 Temperature') }}
type: Label
row: 1
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('25℃') }}

[menu home_menu down_grid lower_right_grid nozzle_extruder nozzle_extruder_grid nozzle2_icon]
name:  {{ gettext('Nozzle2 Icon') }}
type: Image
width: 40
height: 40
row: 2
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/nozzle.png') }}

[menu home_menu down_grid lower_right_grid nozzle_extruder nozzle_extruder_grid nozzle2_temperature]
name:  {{ gettext('Nozzle2 Temperature') }}
type: Label
row: 3
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('25℃') }}

[menu home_menu down_grid lower_right_grid wifi]
name:  {{ gettext('WIFI') }}
type: Button
icon: wifi
panel: wifi
row: 0
column: 1
rowspan: 1
columnspan: 1
connect:  {{ gettext('clicked') }}
value:  {{ gettext('WiFi') }}
style: home_menu_button

[menu home_menu down_grid lower_right_grid messages_assistant]
name:  {{ gettext('Messages Assistant') }}
type: Button
icon: messages_assistant
panel: messages_menu
row: 0
column: 2
rowspan: 1
columnspan: 1
style: home_menu_button