[menu lead_screw_lubrication]
name:  {{ gettext('lead_screw_lubrication') }}
type: Grid

[menu lead_screw_lubrication head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu lead_screw_lubrication head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu lead_screw_lubrication head_grid lead_screw_lubrication_label]
name:  {{ gettext('Lead Screw Lubrication Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('丝杆清洁') }}

[menu lead_screw_lubrication lead_screw_lubrication_body_grid]
name:  {{ gettext('Lead Screw Lubrication Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_message_grid]
name:  {{ gettext('Lead Screw Lubrication message Grid') }}
type: Grid
width: 550
height: 500
row: 0
column: 0
rowspan: 7
columnspan: 3

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_message_grid lead_screw_lubrication_message_title]
name:  {{ gettext('Lead Screw Lubrication Message Title') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('无需丝杆清洁') }}

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_message_grid lead_screw_lubrication_progress_bar]
name:  {{ gettext('Lead Screw Lubrication Progress Bar') }}
type: ProgressBar
width: 500
height: 30
row: 1
column: 0
rowspan: 1
columnspan: 1

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_message_grid lead_screw_lubrication_message]
name:  {{ gettext('Lead Screw Lubrication Message') }}
type: TextView
row: 2
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('简介\nZ轴丝杆用于驱动热床沿Z轴上下移动') }}

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_steps_grid]
name:  {{ gettext('Lead Screw Lubrication Steps Grid') }}
type: Grid
width: 400
height: 420
row: 0
column: 3
rowspan: 6
columnspan: 2

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_steps_grid cleaning_steps]
name:  {{ gettext('Cleaning Steps') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('清洁步骤') }}

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_steps_grid cleaning_steps_qr_code]
name:  {{ gettext('Cleaning Steps QR Code') }}
type: Image
width: 360
height: 360
row: 1
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/cleaning_steps_qr_code.jpg') }}

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_complete_button]
name:  {{ gettext('Lead Screw Lubrication Complete Button') }}
type: Button
row: 6
column: 3
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 60
button_width: 200
value:  {{ gettext('完成') }}
style: next_level

[menu lead_screw_lubrication lead_screw_lubrication_body_grid lead_screw_lubrication_later_button]
name:  {{ gettext('Lead Screw Lubrication Later Button') }}
type: Button
row: 6
column: 4
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 60
button_width: 200
value:  {{ gettext('稍后') }}
style: later_button