[menu macro_command]
name:  {{ gettext('macro_command') }}
type: Grid

[menu macro_command head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu macro_command head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu macro_command head_grid macro_command_label]
name:  {{ gettext('Macro Command Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('Macro Command') }}

[menu macro_command macro_command_body_grid]
name:  {{ gettext('Macro Command Body grid') }}
type: Grid
width: 940
height: 500
column_homogeneous: True
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu macro_command macro_command_body_grid cut]
name:  {{ gettext('Cut') }}
type: Button
icon: cut
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 180
button_width: 180
method: cut
value:  {{ gettext('Cutting continuous fiber consumables') }}
style: macro_command_buttons

[menu macro_command macro_command_body_grid stop_chamber_temperature]
name:  {{ gettext('Stop Chamber Temperature') }}
type: Button
icon: chassis_temperature
row: 0
column: 1
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 180
button_width: 180
method: stop_chamber_temperature
value:  {{ gettext('Stop chamber temperature heating') }}
style: macro_command_buttons

[menu macro_command macro_command_body_grid turn_on_pre_print_detection]
name:  {{ gettext('Turn On Pre Print Detection') }}
type: Button
icon: chassis_temperature
row: 0
column: 2
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 180
button_width: 180
method: turn_on_each_detection_bed
value:  {{ gettext('Turn on pre print detection') }}
style: macro_command_buttons

[menu macro_command macro_command_body_grid turn_off_pre_print_detection]
name:  {{ gettext('Turn Off Pre Print Detection') }}
type: Button
icon: chassis_temperature
row: 0
column: 3
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 180
button_width: 180
method: turn_off_each_detection_bed
value:  {{ gettext('Turn off pre print detection') }}
style: macro_command_buttons