[menu messages_menu]
name:  {{ gettext('messages_menu') }}
type: Grid

[menu messages_menu messages_assistant_grid]
name:  {{ gettext('Messages Assistant Grid') }}
type: Grid
column_homogeneous: True
row_homogeneous: True
width: 490
height: 520
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 590
v_height: 455
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu messages_menu messages_assistant_grid messages_assistant]
name:  {{ gettext('Messages Assistant') }}
type: Image
src:  {{ gettext('images/messages_assistant.png') }}
width: 150
height: 150
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 150
v_height: 150
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu messages_menu messages_grid]
name:  {{ gettext('Messages Grid') }}
type: Grid
column_homogeneous: True
row_homogeneous: True
width: 490
height: 520
column: 1
row: 0
columnspan: 1
rowspan: 1
v_width: 590
v_height: 455
v_column: 0
v_row: 1
v_columnspan: 1
v_rowspan: 1

[menu messages_menu messages_grid notice]
name:  {{ gettext('Notice') }}
type: Label
value:  {{ gettext('No information available!') }}
column: 0
row: 0
columnspan: 1
rowspan: 1
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1