[menu nozzle_extruder]
name:  {{ gettext('nozzle_extruder') }}
type: Grid

[menu nozzle_extruder head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 870
height: 50
column_homogeneous: True
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu nozzle_extruder head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu nozzle_extruder head_grid nozzle_extruder_label]
name:  {{ gettext('Nozzle Extruder Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('喷嘴和挤出机') }}

[menu nozzle_extruder nozzle_extruder_body_grid]
name:  {{ gettext('Nozzle Extruder Body Grid') }}
type: Grid
width: 870
height: 350
column_homogeneous: True
row: 1
column: 0
rowspan: 7
columnspan: 4

[menu nozzle_extruder nozzle_extruder_body_grid nozzle_extrude_image]
name:  {{ gettext('Nozzle Extrude Image') }}
type: Image
width: 100
height: 150
row: 1
column: 3
rowspan: 5
columnspan: 2
src:  {{ gettext('images/nozzle_extruder.png') }}

[menu nozzle_extruder nozzle_extruder_body_grid nozzle_extruder_left_button_grid]
name:  {{ gettext('Nozzle Extruder Left Button Grid') }}
type: Grid
width: 300
height: 20
row: 0
column: 0
rowspan: 1
columnspan: 4

[menu nozzle_extruder nozzle_extruder_body_grid nozzle_extruder_left_button_grid left_nozzle]
name:  {{ gettext('Left Nozzle') }}
type: RadioButton
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('左边') }}

[menu nozzle_extruder nozzle_extruder_body_grid left_nozzle_label]
name:  {{ gettext('Left Nozzle Label') }}
type: Label
row: 2
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('左喷嘴') }}

[menu nozzle_extruder nozzle_extruder_body_grid left_nozzle_temperature]
name:  {{ gettext('Left Nozzle Temperature') }}
type: Button
row: 3
column: 0
rowspan: 1
columnspan: 2
value:  {{ gettext('65/65℃') }}

[menu nozzle_extruder nozzle_extruder_body_grid left_nozzle_type]
name:  {{ gettext('Left Nozzle Type') }}
type: Button
icon: nozzle_edit
row: 4
column: 1
rowspan: 2
columnspan: 2
position: RIGHT
method: set_nozzle_type
value:  {{ gettext('标准\n硬化钢\n0.4mm') }}

[menu nozzle_extruder nozzle_extruder_body_grid left_nozzle_up]
name:  {{ gettext('Left Nozzle Up') }}
type: Button
icon: nozzle_up
row: 2
column: 2
rowspan: 1
columnspan: 1

[menu nozzle_extruder nozzle_extruder_body_grid left_nozzle_down]
name:  {{ gettext('Left Nozzle Down') }}
type: Button
icon: nozzle_down
row: 3
column: 2
rowspan: 1
columnspan: 1

[menu nozzle_extruder nozzle_extruder_body_grid nozzle_extruder_right_button_grid]
name:  {{ gettext('Nozzle Extruder Right Button Grid') }}
type: Grid
width: 300
height: 20
row: 0
column: 5
rowspan: 1
columnspan: 4

[menu nozzle_extruder nozzle_extruder_body_grid nozzle_extruder_right_button_grid right_nozzle]
name:  {{ gettext('Right Nozzle') }}
type: RadioButton
row: 0
column: 5
rowspan: 1
columnspan: 1
value:  {{ gettext('右边') }}

[menu nozzle_extruder nozzle_extruder_body_grid right_nozzle_label]
name:  {{ gettext('Right Nozzle Label') }}
type: Label
row: 2
column: 7
rowspan: 1
columnspan: 1
value:  {{ gettext('右喷嘴') }}

[menu nozzle_extruder nozzle_extruder_body_grid right_nozzle_temperature]
name:  {{ gettext('Right Nozzle Temperature') }}
type: Button
row: 3
column: 6
rowspan: 1
columnspan: 2
value:  {{ gettext('65/65℃') }}

[menu nozzle_extruder nozzle_extruder_body_grid right_nozzle_type]
name:  {{ gettext('Right Nozzle Type') }}
type: Button
icon: nozzle_edit
row: 4
column: 6
rowspan: 2
columnspan: 2
position: RIGHT
method: set_nozzle_type
value:  {{ gettext('标准\n硬化钢\n0.4mm') }}

[menu nozzle_extruder nozzle_extruder_body_grid right_nozzle_up]
name:  {{ gettext('Right Nozzle Up') }}
type: Button
icon: nozzle_up
row: 2
column: 5
rowspan: 1
columnspan: 1

[menu nozzle_extruder nozzle_extruder_body_grid right_nozzle_down]
name:  {{ gettext('Right Nozzle Down') }}
type: Button
icon: nozzle_down
row: 3
column: 5
rowspan: 1
columnspan: 1