[menu print_calibration]
name:  {{ gettext('print_calibration') }}
type: Grid

[menu print_calibration head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu print_calibration head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu print_calibration head_grid calibration_label]
name:  {{ gettext('Calibration Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('打印校准') }}

[menu print_calibration head_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
row: 0
column: 2
rowspan: 1
columnspan: 1
value:  {{ gettext('占位符') }}

[menu print_calibration head_grid next_level]
name:  {{ gettext('Next Level') }}
type: Button
row: 0
column: 4
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 15
button_width: 150
value:  {{ gettext('开始') }}
style: next_level

[menu print_calibration print_calibration_body_grid]
name:  {{ gettext('Print Calibration Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 1
row_spacing: 1

[menu print_calibration print_calibration_body_grid motor_noise_reduction]
name:  {{ gettext('Motor Noise Reduction') }}
type: CheckButton
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('电机降噪(12分钟)') }}

[menu print_calibration print_calibration_body_grid vibration_compensation]
name:  {{ gettext('Vibration Compensation') }}
type: CheckButton
row: 1
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('振动补偿(4分钟)') }}

[menu print_calibration print_calibration_body_grid automatic_hotbed_leveling]
name:  {{ gettext('Automatic Hotbed Leveling') }}
type: CheckButton
row: 2
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('自动热床调平(30分钟)') }}

[menu print_calibration print_calibration_body_grid high_temperature_hotbed]
name:  {{ gettext('High Temperature Hotbed') }}
type: CheckButton
row: 3
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('高温热床调平(30分钟)') }}

[menu print_calibration print_calibration_body_grid nozzle_offset_calibration]
name:  {{ gettext('Nozzle Offset Calibration') }}
type: CheckButton
row: 4
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('喷嘴偏移校准(3分钟)') }}