[menu print_file_list]
name:  {{ gettext('print_file_list') }}
type: Grid

[menu print_file_list head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu print_file_list head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu print_file_list head_grid onboard_storage]
name:  {{ gettext('Onboard Storage') }}
type: Button
row: 0
column: 1
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150
value:  {{ gettext('Onboard Storage') }}

[menu print_file_list head_grid usb]
name:  {{ gettext('USB') }}
type: Button
row: 0
column: 2
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150
value:  {{ gettext('USB') }}

[menu print_file_list head_grid refresh]
name:  {{ gettext('Refresh') }}
type: Button
icon: refresh
row: 0
column: 3
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150
method: refresh_loading

[menu print_file_list head_grid print_busy]
name:  {{ gettext('Print Busy') }}
type: Button
row: 0
column: 4
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150
value:  {{ gettext('Printer is busy') }}
style: waring_button
visible: False

[menu print_file_list file_list_body_grid]
name:  {{ gettext('File List Body Grid') }}
type: Grid
width: 970
height: 530
column_homogeneous: True
row: 1
column: 0
rowspan: 1
columnspan: 4