[menu print_file_list]
name:  {{ gettext('print_file_list') }}
type: Grid

[menu print_file_list head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 430
v_height: 70
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu print_file_list head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
icon: back
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 90
v_button_height: 60
width: 50
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 40
v_height: 40
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu print_file_list head_grid onboard_storage]
name:  {{ gettext('Onboard Storage') }}
type: Button
value:  {{ gettext('Onboard Storage') }}
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 70
v_button_height: 60
column: 1
row: 0
columnspan: 1
rowspan: 1
v_column: 1
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu print_file_list head_grid usb]
name:  {{ gettext('USB') }}
type: Button
value:  {{ gettext('USB') }}
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 70
v_button_height: 60
column: 2
row: 0
columnspan: 1
rowspan: 1
v_column: 2
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu print_file_list head_grid refresh]
name:  {{ gettext('Refresh') }}
type: Button
method: refresh_loading
icon: refresh
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 70
v_button_height: 60
column: 3
row: 0
columnspan: 1
rowspan: 1
v_column: 3
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu print_file_list head_grid print_busy]
name:  {{ gettext('Print Busy') }}
type: Button
value:  {{ gettext('Printer is busy') }}
visible: False
style: waring_button
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 70
v_button_height: 60
column: 4
row: 0
columnspan: 1
rowspan: 1
v_column: 4
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu print_file_list file_list_body_grid]
name:  {{ gettext('File List Body Grid') }}
type: Grid
column_homogeneous: True
width: 970
height: 530
column: 0
row: 1
columnspan: 4
rowspan: 1
v_width: 430
v_height: 665
v_column: 0
v_row: 1
v_columnspan: 5
v_rowspan: 1