[menu speed_control]
name:  {{ gettext('speed_control') }}
type: Grid

[menu speed_control head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 870
height: 50
column_homogeneous: True
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu speed_control head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu speed_control head_grid speed_label]
name:  {{ gettext('Speed Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('速度') }}

[menu speed_control speed_control_body_grid]
name:  {{ gettext('Speed Control Body Grid') }}
type: Grid
width: 870
height: 350
column_homogeneous: True
row: 1
column: 0
rowspan: 5
columnspan: 2

[menu speed_control speed_control_body_grid speed_nozzle_image]
name:  {{ gettext('Speed Nozzle Image') }}
type: Image
width: 200
height: 300
row: 0
column: 0
rowspan: 5
columnspan: 1
src:  {{ gettext('images/speed_nozzle.png') }}

[menu speed_control speed_control_body_grid speed_control_message]
name:  {{ gettext('Speed Control Message') }}
type: Label
row: 5
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('推荐使用标准模式，使用运动模式、狂暴模式\n能提升打印速度，但可能影响打印质量') }}

[menu speed_control speed_control_body_grid furious_model]
name:  {{ gettext('furious Model') }}
type: Button
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('狂暴(166%%)') }}
style: speed_control_button

[menu speed_control speed_control_body_grid sport_model]
name:  {{ gettext('Sport Model') }}
type: Button
row: 1
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('运动(124%%)') }}
style: speed_control_button

[menu speed_control speed_control_body_grid standard_model]
name:  {{ gettext('Standard Model') }}
type: Button
row: 2
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('标准(100%%)') }}
style: speed_control_button

[menu speed_control speed_control_body_grid mute_model]
name:  {{ gettext('Mute Model') }}
type: Button
row: 3
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('静音(50%%)') }}
style: speed_control_button