[menu speed_control]
name:  {{ gettext('speed_control') }}
type: Grid

[menu speed_control head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu speed_control head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu speed_control head_grid speed_label]
name:  {{ gettext('Speed Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('Speed') }}

[menu speed_control speed_control_body_grid]
name:  {{ gettext('Speed Control Body Grid') }}
type: Grid
width: 970
height: 530
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu speed_control speed_control_body_grid speed_nozzle_image]
name:  {{ gettext('Speed Nozzle Image') }}
type: Image
width: 200
height: 330
row: 0
column: 0
rowspan: 3
columnspan: 2
src:  {{ gettext('images/speed_nozzle.png') }}

[menu speed_control speed_control_body_grid speed_control_message]
name:  {{ gettext('Speed Control Message') }}
type: Label
row: 3
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('Recommend using standard mode!') }}

[menu speed_control speed_control_body_grid furious_mode]
name:  {{ gettext('furious Mode') }}
type: Button
row: 0
column: 2
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 110
button_width: 450
method: change_print_speed
value:  {{ gettext('Furious(166%%)') }}
style: speed_control_button

[menu speed_control speed_control_body_grid sport_mode]
name:  {{ gettext('Sport Mode') }}
type: Button
row: 1
column: 2
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 110
button_width: 450
method: change_print_speed
value:  {{ gettext('Sport(124%%)') }}
style: speed_control_button

[menu speed_control speed_control_body_grid standard_mode]
name:  {{ gettext('Standard Mode') }}
type: Button
row: 2
column: 2
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 110
button_width: 450
method: change_print_speed
value:  {{ gettext('Standard(100%%)') }}
style: select_speed_control_button

[menu speed_control speed_control_body_grid mute_mode]
name:  {{ gettext('Mute Mode') }}
type: Button
row: 3
column: 2
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 110
button_width: 450
method: change_print_speed
value:  {{ gettext('Mute(50%%)') }}
style: speed_control_button