[menu speed_control]
name:  {{ gettext('speed_control') }}
type: Grid

[menu speed_control head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 430
v_height: 70
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu speed_control head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
icon: back
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 90
v_button_height: 60
width: 50
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 40
v_height: 40
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu speed_control head_grid speed_label]
name:  {{ gettext('Speed Label') }}
type: Label
value:  {{ gettext('Speed') }}
column: 1
row: 0
columnspan: 1
rowspan: 1
v_column: 1
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu speed_control speed_control_body_grid]
name:  {{ gettext('Speed Control Body Grid') }}
type: Grid
width: 970
height: 530
column: 0
row: 1
columnspan: 4
rowspan: 5
v_width: 490
v_height: 670
v_column: 0
v_row: 1
v_columnspan: 1
v_rowspan: 5

[menu speed_control speed_control_body_grid speed_nozzle_image]
name:  {{ gettext('Speed Nozzle Image') }}
type: Image
src:  {{ gettext('images/speed_nozzle.png') }}
width: 200
height: 330
column: 0
row: 0
columnspan: 2
rowspan: 3
v_width: 200
v_height: 330
v_column: 0
v_row: 0
v_columnspan: 2
v_rowspan: 3

[menu speed_control speed_control_body_grid speed_control_message]
name:  {{ gettext('Speed Control Message') }}
type: Label
value:  {{ gettext('Recommend using standard mode!\nRecommend using standard mode!') }}
column: 0
row: 3
columnspan: 1
rowspan: 1
v_column: 0
v_row: 3
v_columnspan: 2
v_rowspan: 2

[menu speed_control speed_control_body_grid furious_mode]
name:  {{ gettext('furious Mode') }}
type: Button
value:  {{ gettext('Furious(166%%)') }}
method: change_print_speed
style: speed_control_button
hexpand: False
vexpand: False
button_width: 450
button_height: 110
v_button_width: 200
v_button_height: 100
column: 2
row: 0
columnspan: 1
rowspan: 1
v_column: 0
v_row: 5
v_columnspan: 1
v_rowspan: 1

[menu speed_control speed_control_body_grid sport_mode]
name:  {{ gettext('Sport Mode') }}
type: Button
value:  {{ gettext('Sport(124%%)') }}
method: change_print_speed
style: speed_control_button
hexpand: False
vexpand: False
button_width: 450
button_height: 110
v_button_width: 200
v_button_height: 100
column: 2
row: 1
columnspan: 1
rowspan: 1
v_column: 1
v_row: 5
v_columnspan: 1
v_rowspan: 1

[menu speed_control speed_control_body_grid standard_mode]
name:  {{ gettext('Standard Mode') }}
type: Button
value:  {{ gettext('Standard(100%%)') }}
method: change_print_speed
style: select_speed_control_button
hexpand: False
vexpand: False
button_width: 450
button_height: 110
v_button_width: 200
v_button_height: 100
column: 2
row: 2
columnspan: 1
rowspan: 1
v_column: 0
v_row: 6
v_columnspan: 1
v_rowspan: 1

[menu speed_control speed_control_body_grid mute_mode]
name:  {{ gettext('Mute Mode') }}
type: Button
value:  {{ gettext('Mute(50%%)') }}
method: change_print_speed
style: speed_control_button
hexpand: False
vexpand: False
button_width: 450
button_height: 110
v_button_width: 200
v_button_height: 100
column: 2
row: 3
columnspan: 1
rowspan: 1
v_column: 1
v_row: 6
v_columnspan: 1
v_rowspan: 1