[menu sport_calibration]
name:  {{ gettext('sport_calibration') }}
type: Grid

[menu sport_calibration head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu sport_calibration head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu sport_calibration head_grid calibration_label]
name:  {{ gettext('Calibration Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('运动精度校准') }}

[menu sport_calibration sport_calibration_body_grid]
name:  {{ gettext('Sport Calibration Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu sport_calibration sport_calibration_body_grid sport_calibration_message_grid]
name:  {{ gettext('Sport Calibration message Grid') }}
type: Grid
width: 550
height: 500
row: 0
column: 0
rowspan: 7
columnspan: 3

[menu sport_calibration sport_calibration_body_grid sport_calibration_message_grid sport_calibration_message]
name:  {{ gettext('Sport Calibration message') }}
type: TextView
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('运动精度校准') }}

[menu sport_calibration sport_calibration_body_grid sport_calibration_image_grid]
name:  {{ gettext('Sport Calibration Image Grid') }}
type: Grid
width: 400
height: 420
row_homogeneous: True
column_homogeneous: True
row: 0
column: 3
rowspan: 6
columnspan: 2

[menu sport_calibration sport_calibration_body_grid sport_calibration_image_grid sport_calibration_image]
name:  {{ gettext('Sport Calibration Image') }}
type: Image
width: 360
height: 400
row: 0
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/sport_calibration.jpg') }}

[menu sport_calibration sport_calibration_body_grid sport_calibration_start_button]
name:  {{ gettext('Sport Calibration Start Button') }}
type: Button
row: 6
column: 3
rowspan: 1
columnspan: 2
hexpand: False
vexpand: False
button_height: 60
button_width: 400
src:  {{ gettext('iamges/sport_calibration.jpg') }}
value:  {{ gettext('开\t始') }}
style: next_level