[menu wifi]
name:  {{ gettext('wifi') }}
type: Grid

[menu wifi head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 560
v_height: 100
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
icon: back
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 90
v_button_height: 80
width: 50
height: 50
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 40
v_height: 40
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi head_grid wifi_label]
name:  {{ gettext('WIFI Label') }}
type: Label
value:  {{ gettext('WiFi') }}
column: 1
row: 0
columnspan: 1
rowspan: 1
v_column: 1
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi head_grid space_label]
name:  {{ gettext('Space Label') }}
type: Label
value:  {{ gettext('占位符') }}
column: 2
row: 0
columnspan: 1
rowspan: 1
v_column: 2
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi head_grid reload_wifi]
name:  {{ gettext('Reload Wifi') }}
type: Button
method: reload_wifi
icon: refresh
hexpand: False
vexpand: False
button_width: 150
button_height: 50
v_button_width: 90
v_button_height: 80
column: 4
row: 0
columnspan: 1
rowspan: 1
v_column: 4
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi wifi_body_grid]
name:  {{ gettext('WIFI Body grid') }}
type: Grid
width: 940
height: 500
column: 0
row: 1
columnspan: 1
rowspan: 5
v_width: 560
v_height: 600
v_column: 0
v_row: 1
v_columnspan: 1
v_rowspan: 5

[menu wifi wifi_body_grid wifi_switch_grid]
name:  {{ gettext('WIFI Switch Grid') }}
type: Grid
width: 940
height: 30
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 510
v_height: 60
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi wifi_body_grid wifi_switch_grid wifi_switch_label]
name:  {{ gettext('WIFI Switch Label') }}
type: Label
value:  {{ gettext('WiFi') }}
column: 0
row: 0
columnspan: 1
rowspan: 1
v_column: 0
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi wifi_body_grid wifi_switch_grid wifi_ip]
name:  {{ gettext('Wifi Ip') }}
type: Label
value:  {{ gettext('IP:?') }}
column: 1
row: 0
columnspan: 1
rowspan: 1
v_column: 1
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi wifi_body_grid wifi_switch_grid wifi_switch]
name:  {{ gettext('WIFI Switch') }}
type: Switch
value:  {{ gettext('True') }}
column: 2
row: 0
columnspan: 1
rowspan: 1
v_column: 2
v_row: 0
v_columnspan: 1
v_rowspan: 1

[menu wifi wifi_body_grid wifi_message_grid]
name:  {{ gettext('WIFI Message Grid') }}
type: Grid
width: 940
height: 30
column: 0
row: 0
columnspan: 1
rowspan: 1
v_width: 510
v_height: 500
v_column: 0
v_row: 1
v_columnspan: 1
v_rowspan: 1