[menu xyz_axis_cleaning]
name:  {{ gettext('xyz_axis_cleaning') }}
type: Grid

[menu xyz_axis_cleaning head_grid]
name:  {{ gettext('Head Grid') }}
type: Grid
width: 970
height: 50
row: 0
column: 0
rowspan: 1
columnspan: 1

[menu xyz_axis_cleaning head_grid go_back]
name:  {{ gettext('Go Back') }}
type: Button
width: 50
height: 50
icon: back
row: 0
column: 0
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 50
button_width: 150

[menu xyz_axis_cleaning head_grid xyz_axis_cleaning_label]
name:  {{ gettext('XYZ Axis Cleaning Label') }}
type: Label
row: 0
column: 1
rowspan: 1
columnspan: 1
value:  {{ gettext('XYZ轴清洁') }}

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid]
name:  {{ gettext('XYZ Axis Cleaning Body grid') }}
type: Grid
width: 940
height: 500
row: 1
column: 0
rowspan: 5
columnspan: 4

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_message_grid]
name:  {{ gettext('XYZ Cleaning message Grid') }}
type: Grid
width: 550
height: 500
row: 0
column: 0
rowspan: 7
columnspan: 3

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_message_grid xyz_cleaning_message_title]
name:  {{ gettext('XYZ Cleaning Message Title') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('无需清洁') }}

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_message_grid xyz_cleaning_progress_bar]
name:  {{ gettext('XYZ Cleaning Progress Bar') }}
type: ProgressBar
width: 500
height: 30
row: 1
column: 0
rowspan: 1
columnspan: 1

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_message_grid xyz_cleaning_message]
name:  {{ gettext('XYZ Cleaning Message') }}
type: TextView
row: 2
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('简介\n定期的清洁和润滑XYZ轴体') }}

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_steps_grid]
name:  {{ gettext('XYZ Cleaning Steps Grid') }}
type: Grid
width: 400
height: 420
row: 0
column: 3
rowspan: 6
columnspan: 2

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_steps_grid xyz_clean_steps]
name:  {{ gettext('XYZ Clean Steps') }}
type: Label
row: 0
column: 0
rowspan: 1
columnspan: 1
value:  {{ gettext('清洁步骤') }}

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_steps_grid xyz_cleaning_steps_qr_code]
name:  {{ gettext('XYZ Cleaning Steps QR Code') }}
type: Image
width: 360
height: 360
row: 1
column: 0
rowspan: 1
columnspan: 1
src:  {{ gettext('images/cleaning_steps_qr_code.jpg') }}

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_complete_button]
name:  {{ gettext('XYZ Cleaning Complete Button') }}
type: Button
row: 6
column: 3
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 60
button_width: 200
value:  {{ gettext('完成') }}
style: next_level

[menu xyz_axis_cleaning xyz_axis_cleaning_body_grid xyz_cleaning_later_button]
name:  {{ gettext('XYZ Cleaning Later Button') }}
type: Button
row: 6
column: 4
rowspan: 1
columnspan: 1
hexpand: False
vexpand: False
button_height: 60
button_width: 200
value:  {{ gettext('稍后') }}
style: later_button